version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: jnyo/docker-hugo-firebase:latest // Hugo Static Site Generator v0.32.3 linux/amd64 BuildDate: 2018-01-08T11:10:39Z
      - image: inductor/hugo-firebase-tools:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: "sync theme submodule"
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: "check Hugo version"
          command: hugo version
      - run:
          name: "Run Hugo"
          command: hugo -t blackburn -v
      - run:
          name: "check artifact"
          command: ls -lRa
      - deploy:
          branch: master
          command: firebase deploy --token "$FIREBASE_TOKEN"
        
