version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: jnyo/docker-hugo-firebase:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -t slim
      - deploy:
          branch: master
          command: firebase deploy --token "$FIREBASE_TOKEN"
        
